### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getItem' of undefined

### ISSUE THREAD

**Issue by scottydelta** [c3js/c3#1566]
gettting this error on Chromium: 48.0.2564.97 on bar charts when hovered over bars or when clicked on bars. Works perfectly fine on safari. It was working perfectly on Chromium 46.~

Here is the screenshot of the console.

![screen shot 2016-01-29 at 6 33 21 pm](https://cloud.githubusercontent.com/assets/2242189/12692630/0d000a24-c6b7-11e5-86b8-759afdc9cf64.png)

**Comment by pras2015** [comment]
Having the same issue in Chrome Version 48.0.2564.97 

Works as expected in Firefox 44.0 and IE 11

**Comment by vipul-jain** [comment]
Uncaught TypeError: Cannot read property 'getItem' of undefined.
Works before chrome update. 

c3_chart_internal_fn.isWithinBar = function (that) {
        var mouse = this.d3.mouse(that), box = that.getBoundingClientRect(),
            seg0 = **that.pathSegList.getItem(0), seg1 = that.pathSegList.getItem(1),**
            x = Math.min(seg0.x, seg1.x), y = Math.min(seg0.y, seg1.y),
            w = box.width, h = box.height, offset = 2,
            sx = x - offset, ex = x + w + offset, sy = y + h + offset, ey = y - offset;
        return sx < mouse[0] && mouse[0] < ex && ey < mouse[1] && mouse[1] < sy;
    };

**Comment by Roywcm** [comment]
Same error here.
Chrome version: 48.0.2564.97

**Comment by Roywcm** [comment]
#1564

**Comment by sole6** [comment]
same here with chrome- Version 48.0.2564.97 m
works fine on firefox though

**Comment by Roywcm** [comment]
Temporary fix: https://github.com/progers/pathseg

**Comment by kjantzer** [comment]
Thanks @Roywcm , that did the trick.

**Comment by paulbrab** [comment]
@Roywcm worked for me too. Would be nice to get the library updated with the fix though.

**Comment by bt** [comment]
+1, please merge #1564 into master.

**Comment by aendrew** [comment]
Hi all, apologies for the delay in getting to this (rather critical) issue. I've merged #1566 into the new [`dev`](https://github.com/masayuki0812/c3/tree/dev) branch, which is where I'll by merging in the current tranch of PRs for the foreseeable future. Once Masayuki is able to review the `dev` branch, it'll be merged into `master`.

To use the `dev` branch in your projects, do the following:

* Bower:
`bower install c3#dev --save`
* NPM:
`npm install c3#dev --save`

Please let me know if you have any issues. Thanks!

**Comment by Paulsky** [comment]
Hi Aendrew,

I installed the dev branch through Bower. But I'm still getting the error 'Cannot read property 'getItem' of undefined'. Can anyone confirm that the dev branch is working in Chrome 48?

**Comment by brayann** [comment]
Works for me, thanks. Question though: can the dev branch be trusted to use in production? If not, any plans of merging this into a new release? @aendrew

**Comment by aendrew** [comment]
@brayann The `dev` branch is currently the `master` branch with a few tested PRs merged in. It's intended to help push forward to 0.4.12 while @masayuki0812 puts the finishing touches on 0.4.11. As such, it's probably not the most stable thing. 

From what I understand, @masayuki0812 is planning a new release fairly soon. I don't see any reason why this wouldn't be in it.

**Comment by aendrew** [comment]
I'm actually going to reopen this issue until the fix is in `master` so as to increase visibility. It'd be really bad if 0.4.11 went out without this.

**Comment by xtreemrage** [comment]
@Paulsky 
This works for me with bower (`bower -v = 1.7.7`)

**Comment by roshansachan** [comment]
I pulled the dev branch and noticed that it was still not working. I tried using the unminified version of dev branch to dig in to the issue but strangely the error was gone. Strange but the error comes only when using the c3.min.js and works fine with c3.js .

**Comment by vladimirprieto** [comment]
@roshansachan was right. i downloaded dev branch and try with minified version, didn't work just the c3.js works.

Chrome 49.0.2623.87 (64-bit)

**Comment by aendrew** [comment]
Anyone having issues with the `dev` branch, please do the following:

1. Run `npm install` to install all the build dependencies.
2. Run `grunt` to build all the distributed files.

I haven't been updating the build files in the dev version because it it makes merging changes easier. Please don't use Bower with the `dev` branch for the moment!

**Comment by masayuki0812** [comment]
This has been merged into master as 0.4.11. Thank you!

**Comment by nosaj311** [comment]
I'm coming up with a similar issue where the onclick simply does nothing in my line chart. I've tried setting breakpoints in the C3 source in the obvious places where "data_onclick" is called, but none of the 3 instances ever get triggered. Is there still an issue in 0.4.11?

**Comment by alundiak** [comment]
2023 and this is still not fixed? 
I use D3 `v7.8.3` and `0.7.20`.


```

  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.3/d3.js"
    integrity="sha512-3+z8kjFkfZsDUaZ/GM0hNFvH7UXYqAwCN+KHbpE3YUvOdQLKRELYb63J+o7Dg/cus1cy181mHr1Je+c8k/Xv8Q=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.20/c3.css"
    integrity="sha512-GQSxWe9Cj4o4EduO7zO9HjULmD4olIjiQqZ7VJuwBxZlkWaUFGCxRkn39jYnD2xZBtEilm0m4WBG7YEmQuMs5Q=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.20/c3.js"
    integrity="sha512-11Z4MD9csmC3vH8Vd0eIPJBQu3uEHEqeznWEt3sLBCdQx3zm9mJbBcJH8WTcyGY9EXDE81BNpjE2vLosPK8cFQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

```

What is going on? :)
